title: Introduction to Bender
tagline: Take your first steps in the world of futurama
description: If you are looking for a quick and fun introduction to the exciting world of futurama, this course is for you. 
template:
  name: bender-101
  repo: bender-101-template
  description: "A robot powered training repository :robot:"
before:
  - type: createIssue
    title: Welcome
    body: 01-welcome.md
  - type: updateBranchProtection

steps:
  - title: Who is Bender?
    description: Get to know Bender up close and personal
    event: issue_comment.created
    actions:
      - type: createIssue
        title: Bender's best Friend
        body: 02-benders-friend.md
        # Store the response for this new issue by assigning an action_id
        action_id: new_issue
        # Close the issue the user just commented on
      - type: closeIssue
        # Respond in the issue the user just commented on
      - type: respond
        with: 01_successful-close.md
        # Include a `data` object to provide some template variables
        data:
          # Reference the response of the `new_issue` action
          nextIssueUrl: '%actions.new_issue.data.html_url%'


tags:
  - Learning Lab
