title: Introduction to Bender
tagline: Take your first steps in the world of futurama
description: If you are looking for a quick and fun introduction to the exciting world of futurama, this course is for you. 
template:
  name: bender-101
  repo: bender-101-template
  description: "A robot powered introduction repository :robot:"
before:
  - type: createIssue
    title: Welcome
    body: 01-welcome.md
  - type: updateBranchProtection

steps:
  - title: Character Information
    description: Get to know Bender's character information
    event: issue_comment.created
    actions:
      - type: createIssue
        title: Bender's best Friend
        body: 02-benders-friend.md
        # Store the response for this new issue by assigning an action_id
        action_id: new_issue
        # Close the issue the user just commented on
      - type: closeIssue
        # Respond in the issue the user just commented on
      - type: respond
        with: 01_successful-close.md
        # Include a `data` object to provide some template variables
        data:
          # Reference the response of the `new_issue` action
          nextIssueUrl: '%actions.new_issue.data.html_url%'
          
  - title: Before Planet Express
    description: 
    event: issue_comment.created
    actions:
      - type: createIssue
        title: 
        body: 
        action_id: new_issue
      - type: closeIssue
      - type: respond
        with: 
        data:
          nextIssueUrl: '%actions.new_issue.data.html_url%'

  - title: Personality Traits
    description: 
    event: issue_comment.created
    actions:
      - type: createIssue
        title: 
        body: 
        action_id: new_issue
      - type: closeIssue
      - type: respond
        with: 
        data:
          nextIssueUrl: '%actions.new_issue.data.html_url%'

  - title: Family Tree
    description: 
    event: issue_comment.created
    actions:
      - type: createIssue
        title: 
        body: 
        action_id: new_issue
      - type: closeIssue
      - type: respond
        with: 
        data:
          nextIssueUrl: '%actions.new_issue.data.html_url%'

  - title: Gallery
    description: 
    event: issue_comment.created
    actions:
      - type: createIssue
        title: 
        body: 
        action_id: new_issue
      - type: closeIssue
      - type: respond
        with: 
        data:
          nextIssueUrl: '%actions.new_issue.data.html_url%'


tags:
  - Futurama
